#!/usr/bin/env php
<?php

/**
 * Copyright (c) 2011 Kousuke Ebihara
 * 
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
*/

set_time_limit(0);

require_once 'goutte.phar';
require_once 'lib.php';

define('REDMINE_BASE_URL', 'http://redmine.openpne.jp/');
define('REDMINE_PROJECT_ID', 'op3');
define('DEBUG_OUTPUT', true);

$versions = detect_all_versions();
$issues = get_issues_of_development_versions($versions);

echo 'Detecting backports'.PHP_EOL;
foreach ($issues as $issue) {
    $issue->detectBackports();
}
echo 'Fetching data is completed.'.PHP_EOL;

save_cache_data($issues);
